services:
  es01:
    image: elasticsearch:8.7.0
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./es01-data:/usr/share/elasticsearch/data
    environment:
      node.name: es01
      cluster.name: test-cluster
      network.publish_host: 192.168.0.1
      ELASTIC_PASSWORD: 12345a
  kib:
    image: kibana:8.7.0
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - es01
