services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    volumes:
      - ./jdk:/var/jenkins_home/jdk
    ports:
      - "9000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
