services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PG_MAX_CONNECTIONS:: 100
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data